version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - '4444:4444'
  scraper:
    build: ./scraper
    depends_on:
      - selenium
    ports:
      - '3000:3000'
    environment:
      - PYTHONUNBUFFERED=1
